import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./assets/custom-font.css"; // Import the custom font CSS

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased custom-font`}
      >
        <header>
          <img src="/fdlogofull.svg" alt="Logo" className="logo" />
          <nav>
            <ul>
              <li className="t">
                <a href="/our-mission">OUR MISSION</a>
                <ul>
                  <li><a href="/core-values">CORE VALUES</a></li>
                  <li><a href="/functional-philosophy">FUNCTIONAL PHILOSOPHY</a></li>
                  <li><a href="/faq">FREQUENTLY ASKED QUESTIONS</a></li>
                </ul>
              </li>
              <li className="t">
                <a href="/our-team">OUR TEAM</a>
                <ul>
                  <li><a href="/executive-board">EXECUTIVE BOARD</a></li>
                  <li><a href="/engineering-divisions">ENGINEERING DIVISIONS</a></li>
                  <li><a href="/operations-division">OPERATIONS DIVISION</a></li>
                </ul>
              </li>
              <li className="t">
                <a href="/our-vision">OUR VISION</a>
                <ul>
                  <li><a href="/long-term-goals">LONG TERM GOALS</a></li>
                  <li><a href="/current-projects">CURRENT PROJECTS</a></li>
                </ul>
              </li >
              <li className="t"><a href="/join-us">JOIN US</a></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
